// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onWaterOverrideChange();

int soil_moisture_level;
bool water_low;
bool water_override;

void initProperties(){

  ArduinoCloud.addProperty(soil_moisture_level, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(water_low, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(water_override, READWRITE, ON_CHANGE, onWaterOverrideChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
